name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    services:
      registry:
        image: registry:2
        ports:
        - 5000:5000

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate local metadata for Docker image
      id: meta_developer
      uses: docker/metadata-action@v3
      with:
        images: |
          localhost:5000/waltmoorhouse/zephyr-build

    - name: Generate push metadata for Developer image
      if: ${{ github.event_name != 'pull_request' }}
      id: meta_developer_push
      uses: docker/metadata-action@v3
      with:
        images: |
          docker.io/waltmoorhouse/zephyr-build

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build Developer docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta_developer.outputs.tags }}
        labels: ${{ steps.meta_developer.outputs.labels }}

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Developer docker image
      if: ${{ github.event_name != 'pull_request' }}
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: localhost:5000/waltmoorhouse/zephyr-build:${{ steps.meta_developer.outputs.version }}
        dst: ${{ steps.meta_developer_push.outputs.tags }}
