name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      DOCKER_IMAGE: docker.io/waltmoorhouse/zephyr-build

    steps:
    - name: Setup Docker
      run: sudo snap install docker

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test Build Docker
      if: ${{ github.event_name == 'pull_request' }}
      run: docker build -t ${{ env.DOCKER_IMAGE }} .

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Developer docker image
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.GITHUB_REF_NAME }} .
        docker push ${{ env.DOCKER_IMAGE }}:${{ github.GITHUB_REF_NAME }}
